# Default server configuration.
host: 127.0.0.1
mongo_db: mongodb://localhost:27017/notes
port: 3000
jwt_secret: "57126558685788387720244221M22431"
google:
  id: 879916772461-i7htk1jo48ubv18dbe9pvce4m6lbka9n.apps.googleusercontent.com
  secret: ZH3uaWy7Jtb7jtVRLcRRBdD0
  redirect_uri: http://localhost:3000/auth/google/callback